---

- hosts: all
  become: true
  gather_facts: no
  tasks:
  - name: update repository index
    apt:
      update_cache: yes
  - name: install apache2 package
    apt:
      name: apache2
      state: latest
  - name: install git
    apt:
      name: git
      state: latest
